### PR TITLE
Use size(x) inplace of size(x) + 1

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This should probably be added in new branch.

### CODE REVIEW

**Comment by certik** [comment]
I gave you push access. Go ahead and create a new branch.

**Comment by Shaikh-Ubaid** [comment]
>I gave you push access. Go ahead and create a new branch.

Yes, I am trying to. I am facing some Github Login issue (probably related to vscode editor).

**Comment by Shaikh-Ubaid** [comment]
> > I gave you push access. Go ahead and create a new branch.
> d
> Yes, I am trying to. I am facing some Github Login issue (probably related to vscode editor) while pushing changes to your repository.

Done. I had the origin pointing to `https:://`. While pushing it was needed special authorization. After replacing with the ssh link, it seems to work.

**Comment by Shaikh-Ubaid** [comment]
>I gave you push access. Go ahead and create a new branch.

 Thank you so much for the push access.

**Comment by certik** [comment]
Perfect, thanks!

**Pull request closed without merging**
